# Dependabot configuration for LightRAG
# Keeps dependencies up to date automatically

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for critical dependencies
      # to prevent breaking changes
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pandas"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
    groups:
      # Group related dependencies together
      llm-providers:
        patterns:
          - "openai*"
          - "anthropic*"
          - "xai*"
      storage-backends:
        patterns:
          - "psycopg*"
          - "redis*"
          - "pymongo*"
          - "neo4j*"
          - "qdrant-client*"
      testing:
        patterns:
          - "pytest*"
          - "coverage*"
          - "mock*"
      web-framework:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "starlette*"

  # Node.js dependencies (for WebUI)
  - package-ecosystem: "npm"
    directory: "/lightrag_webui"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "webui"
      - "javascript"
    ignore:
      # Ignore major React updates that might require code changes
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      ui-components:
        patterns:
          - "@radix-ui/*"
          - "lucide-react"
          - "tailwindcss"
      build-tools:
        patterns:
          - "vite*"
          - "@vitejs/*"
          - "typescript"
          - "eslint*"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
